import { Vehicle, Lead } from '@/types';

export const vehicles: Vehicle[] = [
  {
    id: '1',
    model: 'Jeep Commander Overland',
    brand: 'Jeep',
    year: 2023,
    price: 289900,
    mileage: '8.500',
    fuel: 'Diesel',
    transmission: 'Automático 9AT',
    color: 'Cinza Graphite',
    imageUrl: '/car1.jpeg',
    images: ['/car1.jpeg', '/car2.jpeg', '/car3.jpg', '/car4.jpg'],
    status: 'available',
    description: 'Único dono, top de linha, pkg offroad',
    features: ['4x4', 'Suspensão Independent', 'Cambio 9AT', 'Rodas 20"', 'Som Alpine', 'Camera 360', 'Banco Couro', 'Teto Solar'],
    createdAt: '2024-01-15T10:00:00Z',
    extras: {
      engine: '2.0 Turbo',
      horsepower: '270cv',
      torque: '40,8kgfm',
      cylinders: '4cil',
      fuelTank: '60L',
      consumption: '9,2km/L',
      acceleration: '8,5s',
      maxSpeed: '206km/h',
      weight: '2.050kg',
      capacity: '750kg',
      traction: '4x4 Active Drive',
      suspension: 'Independent',
      brakes: 'Disco Ventilado',
      steering: 'Elétrica',
      wheels: '20"',
      tires: '255/50R20',
      dimensions: { length: '4,76m', width: '1,86m', height: '1,73m', wheelbase: '2,78m', groundClearance: '20cm' },
      confort: ['Teto Solar', 'Banco Couro', 'Ar 4 zonas', 'Volante Aquecido'],
      safety: ['Camera 360', 'Sensores', 'Alerta Colisão', 'frenagem Autônoma'],
      technology: ['Apple CarPlay', 'Android Auto', 'Wireless Charging', 'GPS'],
      ownership: 'Único Dono',
      ipva: 'Pago',
      licensed: 'Licenciado',
      inspection: 'Laudo Aprovado',
      accidentfree: 'Sem Sinistro',
      maintenance: 'Concessionária',
      warranty: '3 anos',
    },
  },
  {
    id: '2',
    model: 'Toyota Corolla Cross',
    brand: 'Toyota',
    year: 2024,
    price: 199900,
    mileage: '5.000',
    fuel: 'Híbrido',
    transmission: 'CVT e-CVT',
    color: 'Branco Polar',
    imageUrl: '/car2.jpeg',
    images: ['/car2.jpeg', '/car3.jpg', '/car4.jpg', '/car1.jpeg'],
    status: 'available',
    description: 'Zero km, Garantia total 5 anos',
    features: ['Hybrid', 'Toyota Safety Sense', 'Painel Digital', 'Multimídia 10"', 'Carregador Wireless', 'Faróis LED Matrix'],
    createdAt: '2024-02-01T10:00:00Z',
    extras: {
      engine: '2.0 Hybrid',
      horsepower: '172cv',
      torque: '21,0kgfm',
      cylinders: '4cil',
      fuelTank: '55L',
      consumption: '16,0km/L',
      acceleration: '9,2s',
      maxSpeed: '180km/h',
      weight: '1.620kg',
      traction: 'FWD',
      suspension: 'McPherson',
      brakes: 'Disco',
      steering: 'Elétrica',
      wheels: '17"',
      tires: '225/55R17',
      safety: ['Toyota Safety Sense', 'Pre-Collision', 'Lane Departure', 'Adaptative Cruise'],
      technology: ['10" Multimedia', 'Wireless', 'Push Start', 'Farol Matrix LED'],
      ownership: 'Primeiro Dono',
      ipva: 'Pago',
      licensed: 'Licenciado',
    },
  },
  {
    id: '3',
    model: 'Toyota Hilux SR5',
    brand: 'Toyota',
    year: 2023,
    price: 259900,
    mileage: '32.000',
    fuel: 'Diesel',
    transmission: 'Automático 6AT',
    color: 'Preto',
    imageUrl: '/car3.jpg',
    images: ['/car3.jpg', '/car4.jpg', '/car1.jpeg', '/car2.jpeg'],
    status: 'available',
    description: 'Único dono, revisões concessionária',
    features: ['4x4', 'Spray Bar', 'Protetor Carter', 'Multimídia 9"', 'Camera Ré', 'Farol Neblina', 'Assento Couro'],
    createdAt: '2024-02-10T10:00:00Z',
    extras: {
      engine: '2.8 Turbo',
      horsepower: '204cv',
      torque: '50,9kgfm',
      cylinders: '4cil',
      fuelTank: '80L',
      consumption: '10,5km/L',
      acceleration: '10,1s',
      maxSpeed: '185km/h',
      weight: '2.310kg',
      capacity: '945kg',
      traction: '4x4 Part Time',
      suspension: 'Leaf Spring',
      brakes: 'Disco/Tambor',
      steering: 'Elétrica',
      wheels: '17"',
      tires: '265/65R17',
      ownership: 'Único Dono',
      ipva: 'Pago',
      licensed: 'Licenciado',
      inspection: 'Laudo Aprovado',
      maintenance: 'Concessionária',
    },
  },
  {
    id: '4',
    model: 'Lamborghini Lanzador',
    brand: 'Lamborghini',
    year: 2024,
    price: 2500000,
    mileage: '0',
    fuel: 'Elétrico',
    transmission: 'Automático',
    color: 'Amarelo',
    imageUrl: '/car4.jpg',
    status: 'available',
    description: 'Conceito 100% elétrico, produção limitada',
    features: ['1000cv', 'Ar Condicionado 4 Zonas', 'Painel Holográfico', 'Som Supreme', 'Assentos Esportivos', 'Modo Correr'],
    createdAt: '2024-03-01T10:00:00Z',
    extras: {
      engine: 'Dual Motor',
      horsepower: '1.000cv',
      torque: '1.000Nm',
      fuelTank: '120kWh',
      consumption: '5,0km/kWh',
      acceleration: '2,8s',
      maxSpeed: '300km/h',
      weight: '2.500kg',
      traction: '4WD Elétrico',
      steering: 'Elétrica',
      technology: ['Painel Holográfico', 'Autopilot', 'Over-the-Air'],
      warranty: '5 anos',
    },
  },
  {
    id: '5',
    model: 'Honda Civic EX',
    brand: 'Honda',
    year: 2022,
    price: 159900,
    mileage: '45.000',
    fuel: 'Flex',
    transmission: 'CVT',
    color: 'Preto',
    imageUrl: '/car1.jpeg',
    status: 'available',
    description: 'Completo, único dono',
    features: ['Honda Sensing', 'Cambio CVT', 'Rodas 17"', 'Farol LED'],
    createdAt: '2024-01-05T10:00:00Z',
    extras: {
      engine: '1.5 Turbo',
      horsepower: '173cv',
      torque: '22,4kgfm',
      cylinders: '4cil',
      fuelTank: '47L',
      consumption: '11,5km/L',
      acceleration: '8,9s',
      traction: 'FWD',
      steering: 'Elétrica',
      ownership: 'Único Dono',
      ipva: 'Pago',
    },
  },
  {
    id: '6',
    model: 'Ford Ranger Storm',
    brand: 'Ford',
    year: 2023,
    price: 219900,
    mileage: '18.000',
    fuel: 'Diesel',
    transmission: 'Automático 10AT',
    color: 'Prata',
    imageUrl: '/car2.jpeg',
    status: 'available',
    description: 'Top de linha, 4x4',
    features: ['4x4', 'Som Sony', 'Camera 360', 'Assistência de Faixa'],
    createdAt: '2024-01-10T10:00:00Z',
    extras: {
      engine: '3.0 V6 Turbo',
      horsepower: '250cv',
      torque: '58,1kgfm',
      cylinders: 'V6',
      fuelTank: '80L',
      consumption: '9,5km/L',
      acceleration: '7,8s',
      traction: '4x4',
      suspension: 'Independent',
      ownership: 'Único Dono',
      ipva: 'Pago',
      licensed: 'Licenciado',
      maintenance: 'Concessionária',
    },
  },
  {
    id: '7',
    model: 'Chevrolet S10 High Country',
    brand: 'Chevrolet',
    year: 2022,
    price: 249900,
    mileage: '28.000',
    fuel: 'Diesel',
    transmission: 'Automático 6AT',
    color: 'Preto',
    imageUrl: '/car3.jpg',
    status: 'available',
    description: 'Única dono, revisões em dia',
    features: ['4x4', 'Teclado', 'Multimídia', 'Bancos de Couro'],
    createdAt: '2024-01-20T10:00:00Z',
    extras: {
      engine: '2.8 Turbo',
      horsepower: '200cv',
      torque: '51,0kgfm',
      cylinders: '4cil',
      fuelTank: '76L',
      consumption: '9,8km/L',
      traction: '4x4',
      ownership: 'Único Dono',
      ipva: 'Pago',
      inspection: 'Laudo Aprovado',
    },
  },
  {
    id: '8',
    model: 'Volkswagen Amarok',
    brand: 'Volkswagen',
    year: 2023,
    price: 199900,
    mileage: '22.000',
    fuel: 'Diesel',
    transmission: 'Automático 8AT',
    color: 'Branco',
    imageUrl: '/car4.jpg',
    status: 'available',
    description: 'Único dono, laudo aprovado',
    features: ['4x4', 'Rodas 20"', 'Multimídia', 'Camera Ré'],
    createdAt: '2024-02-05T10:00:00Z',
    extras: {
      engine: '2.0 Biturbo',
      horsepower: '204cv',
      torque: '40,8kgfm',
      cylinders: '4cil',
      fuelTank: '80L',
      consumption: '10,0km/L',
      ownership: 'Único Dono',
      ipva: 'Pago',
      inspection: 'Laudo Aprovado',
    },
  },
  {
    id: '9',
    model: 'Nissan Frontier Pro-4X',
    brand: 'Nissan',
    year: 2022,
    price: 189900,
    mileage: '35.000',
    fuel: 'Diesel',
    transmission: 'Automático 7AT',
    color: 'Laranja',
    imageUrl: '/car1.jpeg',
    status: 'available',
    description: 'Offroad, skid plates',
    features: ['4x4', 'Diferencial Travas', 'Proteção Inferior', 'Farol Neblina'],
    createdAt: '2024-02-10T10:00:00Z',
    extras: {
      engine: '2.3 Biturbo',
      horsepower: '190cv',
      torque: '45,1kgfm',
      cylinders: '4cil',
      fuelTank: '80L',
      traction: '4x4 Part Time',
      ownership: 'Único Dono',
      ipva: 'Pago',
    },
  },
  {
    id: '10',
    model: 'Mitsubishi L200 Triton',
    brand: 'Mitsubishi',
    year: 2023,
    price: 209900,
    mileage: '15.000',
    fuel: 'Diesel',
    transmission: 'Automático 6AT',
    color: 'Preto',
    imageUrl: '/car2.jpeg',
    status: 'available',
    description: 'Única dono, pkg offroad',
    features: ['4x4', 'Cambio 6AT', 'Rodas 18"', 'Multimídia'],
    createdAt: '2024-02-15T10:00:00Z',
    extras: {
      engine: '2.4 Turbo',
      horsepower: '181cv',
      torque: '43,0kgfm',
      cylinders: '4cil',
      fuelTank: '75L',
      consumption: '10,2km/L',
      traction: '4x4 Super Select',
      ownership: 'Único Dono',
      ipva: 'Pago',
    },
  },
  {
    id: '11',
    model: 'GMC Hummer EV',
    brand: 'GMC',
    year: 2024,
    price: 189900,
    mileage: '0',
    fuel: 'Elétrico',
    transmission: 'Automático',
    color: 'Verde',
    imageUrl: '/car3.jpg',
    status: 'available',
    description: '100% elétrico, torque instantâneo',
    features: ['1000Nm torque', 'Modo Terra', 'Regenerativo', '4WD'],
    createdAt: '2024-03-01T10:00:00Z',
    extras: {
      engine: 'Tri Motor',
      horsepower: '1.000cv',
      torque: '1.065Nm',
      consumption: '3,0km/kWh',
      acceleration: '3,3s',
      maxSpeed: '160km/h',
      traction: '4WD',
      warranty: '8 anos',
    },
  },
  {
    id: '12',
    model: 'Ford F-150 Raptor',
    brand: 'Ford',
    year: 2023,
    price: 459900,
    mileage: '12.000',
    fuel: 'V8 EcoBoost',
    transmission: 'Automático 10AT',
    color: 'Azul',
    imageUrl: '/car4.jpg',
    status: 'available',
    description: 'Performance offroad extreme',
    features: ['Suspensão Longa', 'Fox Shocks', 'Modo Baja', 'Michelin BF'],
    createdAt: '2024-03-05T10:00:00Z',
    extras: {
      engine: '3.0 V6 EcoBoost',
      horsepower: '450cv',
      torque: '58,0kgfm',
      cylinders: 'V6',
      fuelTank: '136L',
      consumption: '6,5km/L',
      acceleration: '5,0s',
      maxSpeed: '190km/h',
      weight: '2.750kg',
      capacity: '1.130kg',
      traction: '4x4 Part Time',
      suspension: 'Long Travel FOX',
      wheels: '18" beads',
      tires: '315/70R18',
      ownership: 'Único Dono',
    },
  },
];

export const leads: Lead[] = [
  {
    id: '1',
    vehicleId: '1',
    vehicleModel: 'Jeep Commander Overland',
    customerName: 'João Silva',
    customerPhone: '(17) 99999-1111',
    message: 'Tenho interesse neste carro',
    createdAt: '2024-03-20T14:30:00Z',
  },
  {
    id: '2',
    vehicleId: '2',
    vehicleModel: 'Toyota Corolla Cross Hybrid',
    customerName: 'Maria Santos',
    customerPhone: '(17) 99999-2222',
    message: 'Vocês entregam em outra cidade?',
    createdAt: '2024-03-21T09:15:00Z',
  },
];

export const storeInfo = {
  name: 'Flash Multimarcas',
  address: 'Rua Av Prestes Maia, 2566, Votuporanga/SP',
  phone: '(17) 99758-3742',
  whatsapp: '17997583742',
  instagram: '@flashmotorsvotuporanga',
  googleMapsUrl: 'https://www.google.com/maps/place/Flash+Multimarcas/@-20.4230,49.9725,17z',
};

export const ADMIN_CREDENTIALS = {
  username: 'admin',
  password: 'flash2024@',
};